apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: v-link-vm
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: v-link-vm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 128Mi
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            # The default user for the Cirros image is 'cirros'.
            # This cloud-init block sets the password for that user.
            userData: |
              #cloud-config
              user: cirros
              password: password
              chpasswd: { expire: False }
              ssh_pwauth: True
