apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: v-link-vm-fedora
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: v-link-vm-fedora
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
        resources:
          requests:
            memory: 2Gi # Fedora requires more memory than Cirros
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:40
        - name: cloudinitdisk
          cloudInitConfigDrive:
            userData: |
              #cloud-config
              user: fedora
              chpasswd:
                list: |
                  fedora:password
                expire: False
              ssh_pwauth: True
